/*
Developed by Congruent Info-Tech
Class to utilize constants for avoiding HardCoded values
*/
public with sharing class Constants {
  public static final String PICKLIST = 'PICKLIST';
  public static final String SOBJECT_APINAME = 'QuoteLineItem';
  public static final String SUCCESS = 'Success';
  public static final String FAILURE = 'Failure';
  public static final String PRODUCT_LABEL = 'Product';
  public static final String PRODUCT_NAME_API = 'Product2.Name';
  public static final String PRICE_BOOK_NAME = 'Standard Price Book';
  public static final Integer MAX_RECENTHISTORIES_LIMIT = 5;
  public static final Boolean VALIDATE_TRUE = true;
  public static final String DEFAULT_VIEW = 'Default View';
}
